name: _pr_check

on:
  workflow_call:
    inputs:
      # New line separated list of valid commit types => type(scope): message
      commit-types:
        type: string
        required: false
      # New line separated list of valid commit scopes => type(scope): message
      commit-scopes:
        type: string
        required: false

jobs:
  validate-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: ${{ inputs.commit-types }}
          scopes: ${{ inputs.commit-scopes }}

      # Leave a comment if linter reports an error
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! ðŸ‘‹ðŸ¼
            
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
      
      # Hide error message if the PR title has been fixed
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true

  validate-commits:
    name: Validate PR Commits
    runs-on: ubuntu-latest
    steps:
      - uses: Morishiri/block-merge-commits-action@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  pr-labler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '100'
          m_label: 'size/M'
          m_max_size: '500'
          l_label: 'size/L'
          l_max_size: '1000'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note that this PR might be rejected due to its size.
          github_api_url: 'api.github.com'
          files_to_ignore: |
            "*.md"

  label-sync:
    name: Label the PR size
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: EndBug/label-sync@v2
        with:
          # If you want to use a config file, you can put its path or URL here, multiple files are also allowed (more info in the paragraphs below)
          # as multiple:
          config-file: |
            https://raw.githubusercontent.com/EndBug/labels/main/labels.yml
            .github/labels.yml

          # If you want to delete any additional label, set this to true
          delete-other-labels: false

          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.GITHUB_TOKEN }}
